# Generated by Django 4.1.4 on 2022-12-25 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standard",
            name="year",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Année académique"
            ),
        ),
    ]
