# Generated by Django 4.1.4 on 2022-12-25 19:16

import account.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_lesson_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="course.subject",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=account.models.upload_image_path_video,
                validators=[django.core.validators.FileExtensionValidator(["mp4"])],
                verbose_name="contenu vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="course.standard",
            ),
        ),
    ]
